version: '3.8'

services:
  photo-heatmap:  
    image: fbeilke/photo-heatmap-viewer:latest
    container_name: photo-heatmap-viewer
    ports:
      - "8088:8000"
    volumes:
      - ${DATA_DIR:-./data}:/app/data
      - ${LOGS_DIR:-./logs}:/app/logs
      - ${PHOTOS_DIR_LIBRARY1:-./photos/library1}:/photos/library1:ro
      - ${PHOTOS_DIR_LIBRARY2:-./photos/library2}:/photos/library2:ro
    environment:
      TZ: ${TZ:-UTC}
      PHOTO_LIBRARY1_PATH: /photos/library1
      PHOTO_LIBRARY2_PATH: /photos/library2
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
